#pragma once

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SERVER_BASE_URL "http://192.168.x.x:3000"
#define DEVICE_ID "PILLBOX-DEMO-001"
#define DEVICE_API_KEY ""
#define FIRMWARE_VERSION "esp32-s3-mvp-0.2.0"
